### ISSUE TITLE
Close database connection

### ISSUE THREAD

**Issue by mjclemente** [rubiin/nestjs-pgpromise#305]
Should this module close the database connection when the app is shut down?

I'm asking because I noticed in the core TypeORM module, they close the connect `onApplicationShutdown` ([line here](https://github.com/nestjs/typeorm/blob/6acde561118436a2db972f0630dd2eaf3794bcd1/lib/typeorm-core.module.ts#L102)).

Right now I have to do this manually if I don't want a warning during testing that Jest didn't exit properly.

**Comment by rubiin** [comment]
would you like to do a pr?

**Comment by mjclemente** [comment]
Happy to give it a shot, though I'm fairly new to Nest.

I'll put something together for you to review.

**Comment by rubiin** [comment]
> Happy to give it a shot, though I'm fairly new to Nest.
> 
> I'll put something together for you to review.

sure give it a try

**Comment by mjclemente** [comment]
Gave it a shot with #309

**Comment by rubiin** [comment]
Closing this in favor of the PR

**Comment by mjclemente** [comment]
Thanks - can you release the update on npm?

**Comment by rubiin** [comment]
I will release it in an hour
