### ISSUE TITLE
Parameter 'pg' implicitly has an 'any' type in @Inject(NEST_PGPROMISE_CONNECTION)

### ISSUE THREAD

**Issue by Hekkfern** [rubiin/nestjs-pgpromise#385]
The current README.md says the code `constructor(@Inject(NEST_PGPROMISE_CONNECTION) private readonly pg){}` must be added in the service where you want to use pg-promise.

But if the option `"strict": true` is enabled in the tsconfig.json, the next warning don't let the compiler run:

```
{
       .....
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'pg' implicitly has an 'any' type.",
	"source": "ts"
       ......
}
```

The documentation should be updated to use the correct types, as the main advantage of Typescript is the type checking.
Right now, I don't know which type is the "pg" object, so I can solve this issue.

**Comment by rubiin** [comment]
You see here https://github.com/rubiin/nestjs-pgpromise/blob/master/src/nest-pgpromise.service.ts#L9 where the pg instance is being returned from. 
```
pg.IDatabase<{}

```

**Comment by Hekkfern** [comment]
Using `constructor(@Inject(NEST_PGPROMISE_CONNECTION) private readonly pg: IDatabase<any>) {}`, linter accepts it.

However, `pg-promise`package must be added to the project and imported with `import { IDatabase } from 'pg-promise';`.

Shall I make a pull request to change the documentation accordingly?

**Comment by rubiin** [comment]
sure, go ahead, PRs are highly welcomed
