### ISSUE TITLE
"RegisterAsync" Does Not Work

### ISSUE THREAD

**Issue by rosulg** [rubiin/nestjs-pgpromise#4]
Hi!

When trying to inject my config service into **NestPgpromiseModule** the following error occurs:
```typescript
[Nest] 75793   - 10/18/2019, 4:00:08 PM   [ExceptionHandler] Nest can't resolve dependencies of the NEST_PGPROMISE_OPTIONS (?). Please make sure that the argument ConfigService at index [0] is available in the NestPgpromiseModule context.

Potential solutions:
- If ConfigService is a provider, is it part of the current NestPgpromiseModule?
- If ConfigService is exported from a separate @Module, is that module imported within NestPgpromiseModule?
  @Module({
    imports: [ /* the Module containing ConfigService */ ]
  })
 +13ms
```

```typecript
@Module({
  imports: [
    NestPgpromiseModule.registerAsync({
      imports: [ConfigModule],
      useFactory: (configService: ConfigService) => ({connection: configService.config}),
      inject: [ConfigService],
    }),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

I am following the example with TypeORM available [here](https://docs.nestjs.com/techniques/database).

Also when looking at Your source code I can not determine what am I doing wrong.
Can You please provide me with an example how to correctly inject a service into Your module?

I have also provided a repository where this error occurs:
https://github.com/rosulg/example-nest-pg-promise

Best wishes,
Robin Sulg

**Comment by rubiin** [comment]
Will be fixing this as soon as I get some free time

**Comment by rubiin** [comment]
can you check the latest release? @rosulg

**Comment by mjclemente** [comment]
FWIW, the latest version works for me if I `registerAsync` with the `connection` and `initOptions`, but I can't provide the `host`, `user`, etc. Seems like an issue with the interface.

**Comment by rubiin** [comment]
I will look on it asap

**Comment by rubiin** [comment]
> FWIW, the latest version works for me if I `registerAsync` with the `connection` and `initOptions`, but I can't provide the `host`, `user`, etc. Seems like an issue with the interface.

would you like to do a pr?

**Comment by rubiin** [comment]
fixed by latest
