### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by CramericaIndustries** [rubiin/nestjs-pgpromise#441]
## Bug Report
Removed my docker container and image to rebuild both.
Didn't touch the `package.json` file since last rebuild (which worked flawless).

Rebuilding the image failed with `npm install` error...
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: xy-rest-server-nest@0.0.1
npm ERR! Found: @nestjs/common@7.6.4
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"^7.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@">7.6.4" from nestjs-pgpromise@1.4.0
npm ERR! node_modules/nestjs-pgpromise
npm ERR!   nestjs-pgpromise@"^1.3.6" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Looks like `nestjs-pgpromise v1.4.0` demands `@nestjs/common@ v7.6.4`. Is that on purpose?
As a workaround I changed my dependency to nestjs-pgpromise@"1.3.6".

**Comment by rubiin** [comment]
that looks like a typo. I have pushed a patch, should fix that

**Comment by CramericaIndustries** [comment]
That did the trick, it is working now. Thank you very much for the quick fix!

**Comment by rubiin** [comment]
Closing the issue, if the issue resurfaces in future, feel free to open it
