### ISSUE TITLE
Pgp.helpers

### ISSUE THREAD

**Issue by MaxMaioli** [rubiin/nestjs-pgpromise#535]
Hallo, 
in my old node apps i use pgp.helpers a lot, now i am migrating to nestjs, but i can't understand how to user the helpers, can someone help me?

example in old js:

	const cs = new pgp.helpers.ColumnSet(dati, { table: { table: 'mytable', schema: myschema } });

thanks a lot

**Comment by rubiin** [comment]
Let me have a look . I actually haven't used pgp.helpers so I will need to try it out

**Comment by MaxMaioli** [comment]
Hallo, any news on this topic?

thanks a lot

**Comment by sectos** [comment]
After injecting your `NEST_PGPROMISE_CONNECTION` as follows:
```js
constructor(@Inject(NEST_PGPROMISE_CONNECTION) private readonly pg: IDatabase<any>) {}
```

You can then access the underlying PGP object through the `$config` property, for example:

```js
new this.pg.$config.pgp.helpers.ColumnSet(['col1', 'col2']);
```

I'm having trouble finding a reference to this in the pg-promise docs; if anyone else can find it, please post a link.

**Comment by rubiin** [comment]
I will try to update the interfaces so you dont have to use `any`

**Comment by rubiin** [comment]
Updated docs
